server.port: 1280
server.tomcat.connection-timeout: 20000

springdoc:
  api-docs:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: library_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none  # or 'create', 'create-drop', 'validate'
    properties:
      hibernate:
        generate_statistics: "true"
        use_sql_comments: "true"
        format_sql: "true"
        show_sql: "true"
        hbm2ddl.auto: "none"
        jdbc.batch_size: 100
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      mode: always
#      schema-locations: 'classpath:sql/schema.sql'
#    #     data-locations: 'classpath:sql/data.sql'
#http://localhost:1280/swagger-ui/index.html