spring:
  security:
    user:
      name: admin
      password: admin123

  profiles:
    active: local
  application:
    name: library

info:
  app:
    version: 1.0.0

banner:
  time-format: yyyy-MM-dd HH:mm:ss
  current-time: ${current.time}

jwt:
  secret: ENC(p45BL6iWF16/+uh0bs/AibIWbJhjZCKgKxmvPqnMOtb29WRdC9rE/cE38YJ8WxwNz/TjE8rFGDPUbhhCa/94c+p/icN8OnKz7YrBx4N0DCJA67AdWvrXkg==)
  access-token:
    expiration: 900   # 15 minutes = 900 seconds
  refresh-token:
    expiration: 3600  # 60 minutes = 3600 seconds
rate-limit:
  max-attempts: 2
  window-seconds: 10