server.port: 1280
server.tomcat.connection-timeout: 20000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: ENC(bxkNCJ56snvCD5Q+dH9cmLT+MkZ92mCmcPgiqNuXQqM=)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none  # or 'create', 'create-drop', 'validate'
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jasypt:
  encryptor:
    bean: stringEncryptor
