CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";
COMMENT
ON EXTENSION "uuid-ossp" IS 'CREATE GENERATE UNIVERSALLY UNIQUE IDENTIFIERS (UUIDS)';

CREATE TYPE MODERATION_STATE_TYPES AS ENUM ('ON_REVIEW', 'APPROVED', 'DECLINED');
CREATE TYPE USER_STATE_TYPES AS ENUM ('ACTIVE', 'BANNED', 'SUSPENDED');
CREATE TYPE ROLE_TYPE_TYPES AS ENUM ('USER', 'ADMIN');
CREATE TYPE BOOK_ITEM_STATUS_TYPES AS ENUM ('AVAILABLE', 'IN_PROGRESS', 'REMOVED');
CREATE TYPE BOOK_ACTION_TYPES AS ENUM ('ADDED', 'UPDATED', 'BORROWED', 'RETURNED', 'DELETED');

COMMENT
ON TYPE MODERATION_STATE_TYPES IS 'CREATE ENUM TO SET THE COLUMN OF MODERATION_STATE IN USERS TABLE';
COMMENT
ON TYPE USER_STATE_TYPES IS 'CREATE ENUM TO SET THE COLUMN OF USER_STATE IN USERS TABLE';
COMMENT
ON TYPE ROLE_TYPE_TYPES IS 'CREATE ENUM TO SET THE COLUMN OF ROLE_TYPE IN USERS TABLE';
COMMENT
ON TYPE BOOK_ITEM_STATUS_TYPES IS 'CREATE ENUM TO SET THE COLUMN OF STATUS IN BOOKS TABLE';
COMMENT
ON TYPE BOOK_ACTION_TYPES IS 'CREATE ENUM TO SET THE COLUMN OF ACTION_TYPE IN BOOK_ITEM_HISTORY TABLE';

CREATE TABLE USERS
(
    ID               UUID                   DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    USERNAME         VARCHAR(200) UNIQUE                       NOT NULL,
    NAME             VARCHAR(200)                              NOT NULL,
    SURNAME          VARCHAR(200)                              NOT NULL,
    EMAIL            VARCHAR(100)                              NOT NULL,
    PHONE_NUMBER     VARCHAR(15),
    ADDRESS          VARCHAR(300),
    MODERATION_STATE MODERATION_STATE_TYPES DEFAULT 'ON_REVIEW' NOT NULL,
    USER_STATE       USER_STATE_TYPES       DEFAULT 'ACTIVE'    NOT NULL,
    ROLE_TYPE        ROLE_TYPE_TYPES        DEFAULT 'USER'      NOT NULL,
    UPDATED_AT       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT       TIMESTAMP
);
COMMENT
ON TABLE USERS IS 'CREATE THE USERS TABLE TO STORE INFORMATION ABOUT LIBRARY USERS.';

COMMENT
ON COLUMN USERS.MODERATION_STATE IS 'SOFT TIMESTAMP FOR DELETION';

COMMENT
ON COLUMN USERS.ADDRESS IS 'USER ADDRESS OF REGISTRATION';
COMMENT
ON COLUMN USERS.MODERATION_STATE IS 'STATE OF THE USER REGISTRATION';
COMMENT
ON COLUMN USERS.USER_STATE IS 'STATE OF THE USER LIFECYCLE';
COMMENT
ON COLUMN USERS.ROLE_TYPE IS 'USER ROLE IN THE SYSTEM';

CREATE TABLE BOOKS
(
    ID               UUID      DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    TITLE            VARCHAR(200)  NOT NULL,
    AUTHOR           VARCHAR(200)  NOT NULL,
    DESCRIPTION      VARCHAR(1000),
    PUBLISHER        VARCHAR(1000) NOT NULL,
    EDITION          VARCHAR(200),
    PUBLICATION_YEAR INT,
    UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT       TIMESTAMP,
    CONSTRAINT unique_title_edition_year UNIQUE (TITLE, EDITION, PUBLICATION_YEAR)
);
COMMENT
ON COLUMN USERS.ROLE_TYPE IS 'USER ROLE IN THE SYSTEM';
COMMENT
ON COLUMN USERS.ROLE_TYPE IS 'USER ROLE IN THE SYSTEM';
COMMENT
ON COLUMN USERS.ROLE_TYPE IS 'USER ROLE IN THE SYSTEM';
COMMENT
ON TABLE BOOKS IS 'CREATE THE BOOKS TABLE TO STORE INFORMATION ABOUT BOOKS IN THE LIBRARY.';

CREATE TABLE BOOK_ITEMS
(
    ID          UUID                   DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    BOOK_ID     UUID                                       NOT NULL,
    STATUS      BOOK_ITEM_STATUS_TYPES DEFAULT 'AVAILABLE' NOT NULL,
    USER_ID     UUID                   DEFAULT NULL,
    BORROWED_AT TIMESTAMP              DEFAULT NULL,
    RETURNED_AT TIMESTAMP              DEFAULT NULL,
    UPDATED_AT  TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT  TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP              DEFAULT NULL,
    CONSTRAINT FK_BOOK_ITEM_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE NO ACTION,
    CONSTRAINT FK_BOOK_ITEM_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE NO ACTION
);
COMMENT
ON TABLE BOOK_ITEMS IS 'CREATE THE BOOK_ITEMS TABLE TO STORE INFORMATION ABOUT EACH BOOK COPY.';
COMMENT
ON CONSTRAINT FK_BOOK_ITEM_USER ON BOOK_ITEMS IS 'CREATE THE FOREIGN KEY TO THE USERS TABLE';
COMMENT
ON CONSTRAINT FK_BOOK_ITEM_BOOK ON BOOK_ITEMS IS 'CREATE THE FOREIGN KEY TO THE BOOKS TABLE';

CREATE TABLE GENRES
(
    ID   UUID DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    NAME VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE BOOK_GENRES
(
    ID       UUID DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    BOOK_ID  UUID NOT NULL,
    GENRE_ID UUID NOT NULL,
    CONSTRAINT FK_GENRES_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_GENRES_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE CASCADE
);
COMMENT
ON TABLE BOOK_GENRES IS 'CREATE THE BOOK_GENRES TABLE TO STORE INFORMATION ABOUT EACH BOOK GENRE.';
COMMENT
ON CONSTRAINT FK_GENRES_BOOK_ID ON BOOK_GENRES IS 'CREATE THE FOREIGN KEY TO THE BOOKS TABLE';
COMMENT
ON CONSTRAINT FK_GENRES_GENRE_ID ON BOOK_GENRES IS 'CREATE THE FOREIGN KEY TO THE GENRES TABLE';

CREATE TABLE BOOK_ITEM_HISTORY
(
    ID          UUID              DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    ITEM_ID     UUID                                NOT NULL,
    USER_ID     UUID,
    ACTION_AT   TIMESTAMP         DEFAULT CURRENT_TIMESTAMP,
    ACTION_TYPE BOOK_ACTION_TYPES DEFAULT ('ADDED') NOT NULL,

    CONSTRAINT FK_BOOK_ITEM_HISTORY_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE NO ACTION,
    CONSTRAINT FK_BOOK_ITEM_HISTORY_BOOK FOREIGN KEY (ITEM_ID) REFERENCES BOOK_ITEMS (ID) ON DELETE NO ACTION
);
COMMENT
ON COLUMN USERS.ROLE_TYPE IS 'USER ROLE IN THE SYSTEM';
COMMENT
ON COLUMN USERS.ROLE_TYPE IS 'USER ROLE IN THE SYSTEM';
COMMENT
ON TABLE BOOK_ITEM_HISTORY IS 'CREATE THE BOOK_ITEM_HISTORY TABLE TO STORE INFORMATION ABOUT EACH BOOK ACTION.';
COMMENT
ON CONSTRAINT FK_BOOK_ITEM_HISTORY_USER ON BOOK_ITEM_HISTORY IS 'CREATE THE FOREIGN KEY TO THE USERS TABLE';
COMMENT
ON CONSTRAINT FK_BOOK_ITEM_HISTORY_BOOK ON BOOK_ITEM_HISTORY IS 'CREATE THE FOREIGN KEY TO THE BOOKS TABLE';